Repository jenkins-zh/jenkins-zh, pull requests merged in 2020-05, with the labels that each got.

#254 [原创-2020-05-07] Add jcli release v0.0.28
  content/wechat/articles/2020/05/2020-05-07-jcli-v0.0.28.md
  content/wechat/articles/2020/05/2020-05-07-jcli-v0.0.28/jenkins-cli.png
Labels: article

#261 Add an English version of translation submition
  .github/ISSUE_TEMPLATE/translation-en.md
  README.md
  static/.DS_Store
Labels: chore

#219 Add on online meetup
  content/event/beijing-2019-10-25.md
  content/event/online-2020-04-22.md
  content/event/shanghai-2019-09.md
  content/speaker/linuxsuren.json
  layouts/meetup/list.html
  layouts/meetup/single.html
Labels: event

#255 [翻译-2020-05-13] 使用 Nexus OSS 为 Docker 镜像提供代理/缓存功能
  content/wechat/articles/2020/05/2020-05-13-using-nexus-oss-as-a-proxy-cache-for-docker-images.md
  content/wechat/articles/2020/05/2020-05-13-using-nexus-oss-as-a-proxy-cache-for-docker-images/cover.jpg
  content/wechat/articles/2020/05/2020-05-13-using-nexus-oss-as-a-proxy-cache-for-docker-images/createproxy.png
  content/wechat/articles/2020/05/2020-05-13-using-nexus-oss-as-a-proxy-cache-for-docker-images/createrepo.png
  content/wechat/articles/2020/05/2020-05-13-using-nexus-oss-as-a-proxy-cache-for-docker-images/dockerinfo.png
  content/wechat/articles/2020/05/2020-05-13-using-nexus-oss-as-a-proxy-cache-for-docker-images/dockerpull.png
  content/wechat/articles/2020/05/2020-05-13-using-nexus-oss-as-a-proxy-cache-for-docker-images/groupconfiguration.png
  content/wechat/articles/2020/05/2020-05-13-using-nexus-oss-as-a-proxy-cache-for-docker-images/proxyhubconfiguration.png
  content/wechat/articles/2020/05/2020-05-13-using-nexus-oss-as-a-proxy-cache-for-docker-images/proxyprivateconfiguration.png
  content/wechat/articles/2020/05/2020-05-13-using-nexus-oss-as-a-proxy-cache-for-docker-images/realms.png
  content/wechat/articles/2020/05/2020-05-13-using-nexus-oss-as-a-proxy-cache-for-docker-images/showinginnexus.png
Labels: ready

#273 Add meeting note of 2020-05-13
  content/meeting/2020-05-13.md
Labels: chore

#269 [翻译-2020-05-15] Call for user stories -Jenkins is the way
  content/wechat/articles/2020/05/2020-05-15-call-for-user-stories-jenkins-is-the-way.md
  content/wechat/articles/2020/05/2020-05-15-call-for-user-stories-jenkins-is-the-way/cloudbees.png
  content/wechat/articles/2020/05/2020-05-15-call-for-user-stories-jenkins-is-the-way/jenkins-is-the-way-t-shirt.png
  content/wechat/articles/2020/05/2020-05-15-call-for-user-stories-jenkins-is-the-way/jenkins-is-the-way.png
Labels: ready

#278 Update the terms of articles
  .github/PULL_REQUEST_TEMPLATE.md
Labels: chore

#252 [投稿-2020-05-19] add jenkins-kubesphere-partner.md
  content/wechat/articles/2020/04/2020-04-30-jenkins-kubesphere-partner.md
Labels: ready

#281 [翻译-2020-05-25] 版本更新内容
  content/wechat/articles/2020/05/2020-05-25-weekly-release.md
  content/wechat/articles/2020/05/2020-05-25-weekly-release/great-wall.jpeg
Labels: ready
