Repository jenkins-zh/jenkins-zh, pull requests merged in 2020-10, with the labels that each got.

#360 Add a license file
  LICENSE
Labels: chore, hacktoberfest-accepted

#361 [维护] 修改状态
  content/event/online-2020-04-22.md
Labels: hacktoberfest-accepted

#355 [维护] 修改错误路径
  content/tutorial/management/cli/_index.md
Labels: chore, hacktoberfest-accepted

#362 [维护] 更新url地址
  themes/hugo-jenkins-theme/layouts/partials/site-footer.html
Labels: hacktoberfest-accepted

#363 [原创-2020-10-08] GitHub 推出 Codespaces Beta
  content/wechat/articles/2020/10/2020-10-08-github-codespaces.md
  content/wechat/articles/2020/10/2020-10-08-github-codespaces/github-vs-1.png
  content/wechat/articles/2020/10/2020-10-08-github-codespaces/github-vs-2.png
  content/wechat/articles/2020/10/2020-10-08-github-codespaces/github-vs-3.png
  content/wechat/articles/2020/10/2020-10-08-github-codespaces/github-vs-4.png
  content/wechat/articles/2020/10/2020-10-08-github-codespaces/github-vs-5.png
  content/wechat/articles/2020/10/2020-10-08-github-codespaces/github-vs-6.png
  content/wechat/articles/2020/10/2020-10-08-github-codespaces/github-vs-7.png
  content/wechat/articles/2020/10/2020-10-08-github-codespaces/github-vs-8.png
Labels: hacktoberfest-accepted, 原创

#364 [维护] Using bot committer
  .github/workflows/deploy-to-github-page.yaml
Labels: chore, hacktoberfest-accepted

#349 [原创-2020-10-09] Jenkins 每周版更新
  content/wechat/articles/2020/10/2020-10-09-weekly-release.md
  content/wechat/articles/2020/10/2020-10-09-weekly-release/great-wall.jpeg
Labels: 原创

#366 添加新的合作社区
  content/partner/testerhome.md
  static/images/partners/testerhome.png
Labels: chore, hacktoberfest-accepted

#365 [维护] Add a badge for hints count for this repository
  README-zh.md
  README.md
Labels: chore, hacktoberfest-accepted

#350 [原创-2020-10-10] Jenkins 长期版更新
  content/wechat/articles/2020/10/2020-10-10-jenkins-release.md
  content/wechat/articles/2020/10/2020-10-10-jenkins-release/great-wall.jpeg
Labels: 原创

#367 Backup git repo to Code China
  .github/workflows/backup.yaml
Labels: chore, hacktoberfest-accepted

#357 Add a tutorial of Jenkins war installation
  content/tutorial/get-started/install/war.md
Labels: hacktoberfest-accepted, tutorial

#359 [原创-2020-10-12] Jenkins 系列视频教程制作组招募
  content/wechat/articles/2020/10/2020-10-12-contributors-recruit.md
Labels: hacktoberfest-accepted, 原创

#369 [维护] 补充图片和修改内容
  content/wechat/articles/2020/10/2020-10-12-contributors-recruit.md
  content/wechat/articles/2020/10/2020-10-12-contributors-recruit/cover.png
Labels: hacktoberfest-accepted

#370 [运维] Change the url of Jenkins in CSDN blog
  content/about/social-media.md
Labels: hacktoberfest-accepted

#356 [翻译-2020-10-14] 使用 Bitbucket 流水线创建最简单的 CI
  content/wechat/articles/2020/10/2020-10-14-setup-the-simplest-ci-with-bitbucket-pipeline.md
  content/wechat/articles/2020/10/2020-10-14-setup-the-simplest-ci-with-bitbucket-pipeline/cover.jpg
  content/wechat/articles/2020/10/2020-10-14-setup-the-simplest-ci-with-bitbucket-pipeline/deploy.png
  content/wechat/articles/2020/10/2020-10-14-setup-the-simplest-ci-with-bitbucket-pipeline/pipeline-configuration.png
  content/wechat/articles/2020/10/2020-10-14-setup-the-simplest-ci-with-bitbucket-pipeline/pipeline-menu.png
  content/wechat/articles/2020/10/2020-10-14-setup-the-simplest-ci-with-bitbucket-pipeline/project-configuration.png
  content/wechat/articles/2020/10/2020-10-14-setup-the-simplest-ci-with-bitbucket-pipeline/repository-variables.png
Labels: hacktoberfest-accepted, translation

#374 Add huiyingzimu partner
  content/partner/huiyingzimu.md
  static/images/partners/huiyingzimu.png
Labels: hacktoberfest-accepted

#375 [维护] Add link of bilibili
  content/tutorial/_index.md
Labels: chore, hacktoberfest-accepted
