Repository jenkins-zh/jenkins-zh, pull requests merged in 2021-04, with the labels that each got.

#440 添加暑期计划2021项目提议～通过 CLI 对 Jenkins 实现安全升级
  content/about/summer-2021.md
Labels: kind/chore, size/L

#444 增加如何认领以及预计完成日期的说明
  .github/ISSUE_TEMPLATE/translation.md
Labels: kind/chore

#449 2021-04-15-jenkins-operator-sub-project
  content/wechat/articles/2021/04/2021-04-15-jenkins-operator-sub-project.md
  content/wechat/articles/2021/04/2021-04-15-jenkins-operator-sub-project/gopher-butler-256.png
  content/wechat/articles/2021/04/2021-04-15-jenkins-operator-sub-project/tshirt-logo.jpg
Labels: size/M
