Repository jenkins-zh/jenkins-zh, pull requests merged in 2021-07, with the labels that each got.

#454 Configure Plugins with JCasC tutorial translation
  content/wechat/articles/2021/07/2021-07-03-jenkins-JCasC-tutorial-translation.md
  content/wechat/articles/2021/07/2021-07-03-jenkins-JCasC-tutorial-translation/JCasC-logo.jpg
  content/wechat/articles/2021/07/2021-07-03-jenkins-JCasC-tutorial-translation/add-filters-to-view.png
  content/wechat/articles/2021/07/2021-07-03-jenkins-JCasC-tutorial-translation/apply-new-config.png
  content/wechat/articles/2021/07/2021-07-03-jenkins-JCasC-tutorial-translation/dheerajodha.jpg
  content/wechat/articles/2021/07/2021-07-03-jenkins-JCasC-tutorial-translation/download-config-button.png
  content/wechat/articles/2021/07/2021-07-03-jenkins-JCasC-tutorial-translation/naming-the-view.png
  content/wechat/articles/2021/07/2021-07-03-jenkins-JCasC-tutorial-translation/updating-the-jenkins-file.png
  content/wechat/articles/2021/07/2021-07-03-jenkins-JCasC-tutorial-translation/view-final-changes.png
  content/wechat/articles/2021/07/2021-07-03-jenkins-JCasC-tutorial-translation/viewing-changes-in-jenkins-file.png
  content/wechat/articles/2021/07/2021-07-03-jenkins-JCasC-tutorial-translation/yaml-file-on-jenkins-ui.png
  content/wechat/articles/2021/07/2021-07-03-jenkins-JCasC-tutorial-translation/yaml-file-on-local-text-editor.png
Labels: size/L

#455 [维护] 修改图片路径，使用本仓库的，而不是外链
  content/wechat/articles/2021/07/2021-07-03-jenkins-JCasC-tutorial-translation.md
Labels: size/XS

#456 议题公开征集
  content/wechat/articles/2021/07/2091-07-19-call-for-paper.md
  content/wechat/articles/2021/07/2091-07-19-call-for-paper/call-for-papers.jpg
Labels: size/M
