Repository jenkins-zh/jenkins-zh, pull requests merged in 2021-02, with the labels that each got.

#423 [维护] Add file OWNERS
  OWNERS
Labels: kind/chore, size/XS

#422 Add release of jcli v0.0.33
  content/wechat/articles/2021/02/2021-02-02-jcli-v0.0.33.md
  content/wechat/articles/2021/02/2021-02-02-jcli-v0.0.33/jenkins-cli.png
Labels: kind/article, lgtm

#426 [翻译-2020-02-21] Jenkins 贡献者线上会议 - 二月 23 日至 25 日
  content/wechat/articles/2021/02/2021-02-26-jenkins-contributor-summit-online-feb-23-25.md
  content/wechat/articles/2021/02/2021-02-26-jenkins-contributor-summit-online-feb-23-25/cover.jpg
Labels: kind/translation, lgtm, size/L

#427 [维护] 添加梯子续费记录
  content/about/sponsors-list.md
Labels: size/XS
