Repository jenkins-zh/jenkins-zh, pull requests merged in 2021-03, with the labels that each got.

#432 [翻译-2021-03-24] 2020 Google 编程之夏活动总结
  content/wechat/articles/2021/03/2021-03-24-google-summer-of-code-2020-summary.md
  content/wechat/articles/2021/03/2021-03-24-google-summer-of-code-2020-summary/cover.jpg
  content/wechat/articles/2021/03/2021-03-24-google-summer-of-code-2020-summary/jenkins-gsoc-logo.png
  content/wechat/articles/2021/03/2021-03-24-google-summer-of-code-2020-summary/student-photos.png
  content/wechat/articles/2021/03/2021-03-24-google-summer-of-code-2020-summary/swag.jpg
Labels: kind/translation, lgtm, size/XXL

#436 Add meeting notes for 2021 03 03
  content/meeting/2021-03-03.md
Labels: kind/chore, size/S

#434 Change the youtube channel from personal link to the brand link
  themes/hugo-jenkins-theme/layouts/partials/site-footer.html
Labels: kind/chore, size/XS

#439 Add translation update-center-certificate-rotation
  content/wechat/articles/2021/03/2021-03-31-update-center-certificate-rotation.md
  content/wechat/articles/2021/03/2021-03-31-update-center-certificate-rotation/certificate-rotation-opengraph.png
Labels: kind/translation, size/M

#437 Update the sponsor list
  content/sponsor/hogwarts.md
  content/sponsor/juzi.md
  content/sponsor/ucloud.md
  themes/hugo-jenkins-theme/layouts/partials/home-page-sections/sponsors.html
Labels: kind/chore, size/XS

#438 Update the partner list
  content/partner/kubesphere.md
  content/partner/testerhome.md
Labels: kind/chore, size/XS

#433 Add 0N0thing as a reviewer under content/wechat/articles
  content/wechat/articles/OWNERS
Labels: kind/chore, size/XS

#435 Add article Docker image updates
  content/wechat/articles/2021/03/2021-03-29-jenkins-docker-image-update.md
  content/wechat/articles/2021/03/2021-03-29-jenkins-docker-image-update/dockerJenkins.png
Labels: kind/translation, size/XL
